name: Update README with Dynamic Data

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch GitHub Data
      id: fetch_data
      run: |
        USERNAME="${{ github.actor }}"
        USER_DATA=$(curl -s https://api.github.com/users/$USERNAME)
        REPOS_DATA=$(curl -s https://api.github.com/users/$USERNAME/repos?per_page=100)
        PRS_DATA=$(curl -s "https://api.github.com/search/issues?q=type:pr+author:$USERNAME&per_page=100")
        STREAK_DATA=$(curl -s "https://github-readme-streak-stats.herokuapp.com/api?user=$USERNAME")

        # Extract data
        echo "total_repos=$(echo $USER_DATA | jq -r '.public_repos')" >> $GITHUB_ENV
        echo "total_commits=$(echo $USER_DATA | jq -r '.public_repos' | awk '{print $1 * 10}')" >> $GITHUB_ENV  # Placeholder for commits
        echo "current_streak=$(echo $STREAK_DATA | jq -r '.currentStreak.days')" >> $GITHUB_ENV
        echo "total_prs=$(echo $PRS_DATA | jq -r '.total_count')" >> $GITHUB_ENV
        echo "repos_contributed_to=$(echo $REPOS_DATA | jq -r '. | length')" >> $GITHUB_ENV
        echo "open_source_projects=3" >> $GITHUB_ENV  # Placeholder
        LANGUAGES=$(echo $REPOS_DATA | jq -r 'map(.language) | .[]' | sort | uniq -c | sort -rn | awk '{print $2}' | head -n 3 | paste -sd ", ")
        echo "most_used_languages=\"$LANGUAGES\"" >> $GITHUB_ENV

    - name: Display README Content for Debugging
      run: cat README.md

    - name: Update README
      run: |
        echo "Updating README.md with new data"
        sed -i "s/Total Repos:              .*/Total Repos:              ${total_repos}/" README.md
        sed -i "s/Total Commits:            .*/Total Commits:            ${total_commits}/" README.md
        sed -i "s/Current Streak:           .*/Current Streak:           ${current_streak}/" README.md
        sed -i "s/Total PRs:                .*/Total PRs:                ${total_prs}/" README.md
        sed -i "s/Repos Contributed To:     .*/Repos Contributed To:     ${repos_contributed_to}/" README.md
        sed -i "s/Open-Source Projects:     .*/Open-Source Projects:     ${open_source_projects}/" README.md
        sed -i "s/Most Used Languages:      .*/Most Used Languages:      ${most_used_languages}/" README.md

        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add README.md
        git status
        git commit -m "Update README with latest GitHub statistics" || echo "No changes to commit"
        git push
